Class {
	#name : #GtPhlowStencilDataSerializationStrategy,
	#superclass : #GtPhlowDeclarativeSpecification,
	#category : #'GToolkit-RemotePhlow-Stencils'
}

{ #category : #api }
GtPhlowStencilDataSerializationStrategy >> prepareStencilSpecificationForSerializationFor: aStencilSpecification from: aViewSpecification [
]

{ #category : #api }
GtPhlowStencilDataSerializationStrategy >> updateStencilSpecificationAfterDeserializationFor: aStencil from: aViewSpecification [
]
