Extension { #name : #GtPhlowWithSpecificationStencil }

{ #category : #'*GToolkit-RemoteGt-Stencils' }
GtPhlowWithSpecificationStencil >> asElement [ 
	^ self create
]

{ #category : #'*GToolkit-RemoteGt-Stencils' }
GtPhlowWithSpecificationStencil >> create [
	^ self subclassResponsibility
]

{ #category : #'*GToolkit-RemoteGt-Stencils' }
GtPhlowWithSpecificationStencil >> initializeFromStencilSpecification: aStencilSpecification [
]
