Class {
	#name : #GtRemotePhlowExampleCustomInspectActionId,
	#superclass : #GtRemotePhlowBasicId,
	#category : #'GToolkit-RemotePhlow-Examples'
}

{ #category : #accessing }
GtRemotePhlowExampleCustomInspectActionId class >> typeLabel [
	^ 'remotePhlowExampleCustomInspectActionId'
]

{ #category : #converting }
GtRemotePhlowExampleCustomInspectActionId >> asSymbol [
	^ #'remote-example--custom-inspect'
]
