Trait {
	#name : #TGtRemoteLanguageProxySpecificActions,
	#category : #'GToolkit-RemoteGt'
}

{ #category : #'gt - extensions' }
TGtRemoteLanguageProxySpecificActions >> gtActionBrowseFor: anAction [
	<gtProxyAction>

	^ super gtActionBrowseFor: anAction
]

{ #category : #'gt - extensions' }
TGtRemoteLanguageProxySpecificActions >> gtActionInspectFor: anAction [
	<gtProxyAction>

	^ super gtActionInspectFor: anAction
]
