Class {
	#name : 'GtPhlowBasicGlamorousIconNameStencil',
	#superclass : 'GtPhlowNamedIconStencil',
	#category : 'GToolkit-RemotePhlow-Icons'
}

{ #category : 'instance creation' }
GtPhlowBasicGlamorousIconNameStencil class >> close [
	^ self  forIconName: #close
]

{ #category : 'instance creation' }
GtPhlowBasicGlamorousIconNameStencil class >> play [
	^ self  forIconName: #play
]

{ #category : 'instance creation' }
GtPhlowBasicGlamorousIconNameStencil class >> playinspect [
	^ self  forIconName: #playinspect
]

{ #category : 'instance creation' }
GtPhlowBasicGlamorousIconNameStencil class >> remove [
	^ self  forIconName: #remove
]
