Class {
	#name : #GtRemotePhlowDeclarativeViewDetailsDataSource,
	#superclass : #GtRemotePhlowDeclarativeViewDataSource,
	#category : #'GToolkit-RemotePhlow-DeclarativeViews'
}

{ #category : #'as yet unclassified' }
GtRemotePhlowDeclarativeViewDetailsDataSource >> retrieveRowTexts [
	self shouldBeImplemented
]

{ #category : #'as yet unclassified' }
GtRemotePhlowDeclarativeViewDetailsDataSource >> retrieveRowValues [
	self shouldBeImplemented
]
