"
Remote phlow version of GtPhlowViewRefreshContentButtonId.
"
Class {
	#name : #GtRemotePhlowViewRefreshContentButtonId,
	#superclass : #GtRemotePhlowBasicId,
	#category : #'GToolkit-RemotePhlow-PhlowActions'
}

{ #category : #accessing }
GtRemotePhlowViewRefreshContentButtonId class >> typeLabel [
	^ 'remotePhlowViewRefreshContentButtonId'
]

{ #category : #accessing }
GtRemotePhlowViewRefreshContentButtonId >> asSymbol [
	^ #'phlow-view--refresh-content'
]
