Class {
	#name : #GtRemotePhlowExampleInspectItemActionId,
	#superclass : #GtRemotePhlowBasicId,
	#category : #'GToolkit-RemotePhlow-PhlowActions'
}

{ #category : #accessing }
GtRemotePhlowExampleInspectItemActionId class >> typeLabel [
	^ 'remotePhlowExampleInspectItemActionId'
]

{ #category : #converting }
GtRemotePhlowExampleInspectItemActionId >> asSymbol [
	^ #'remote-example--inspect-item'
]
