Class {
	#name : 'GtRemotePhlowPluggableCollectionIterator',
	#superclass : 'GtRemotePhlowUnindexedCollectionIterator',
	#category : 'GToolkit-RemotePhlow-PhlowViews'
}

{ #category : 'accessing' }
GtRemotePhlowPluggableCollectionIterator >> iterationSelector [
	^ iterationSelector
]

{ #category : 'accessing' }
GtRemotePhlowPluggableCollectionIterator >> iterationSelector: aSelector [
	iterationSelector := aSelector
]
