Class {
	#name : #PlpoGtPhlowColumnedTreeViewSpecification,
	#superclass : #PharoLinkProxyObject,
	#traits : 'TPlpoGtPhlowListingViewSpecification + TPlpoGtPhlowTreeViewSpecification',
	#classTraits : 'TPlpoGtPhlowListingViewSpecification classTrait + TPlpoGtPhlowTreeViewSpecification classTrait',
	#category : #'Gt4PharoLink-Proxies'
}

{ #category : #accessing }
PlpoGtPhlowColumnedTreeViewSpecification >> remoteClassName [

	^ #GtPhlowColumnedTreeViewSpecification
]
