"
Inspector examples for a direct local web browser stencil fixture.
"
Class {
	#name : #GtRemotePhlowWebBrowserStencilObjectInspectionExamples,
	#superclass : #GtRemotePhlowWebBrowserStencilLocalInspectionExamples,
	#category : #'GToolkit-RemoteGt-Examples'
}

{ #category : #'examples - setup' }
GtRemotePhlowWebBrowserStencilObjectInspectionExamples >> createTestObject [
	<gtExample>
	^ GtRemotePhlowWebBrowserStencilTestObject new
]
