"
Shared local and simulation inspector examples for web browser stencils.
"
Class {
	#name : #GtRemotePhlowWebBrowserStencilLocalInspectionExamples,
	#superclass : #GtRemotePhlowWebBrowserStencilInspectionExamples,
	#category : #'GToolkit-RemoteGt-Examples'
}

{ #category : #testing }
GtRemotePhlowWebBrowserStencilLocalInspectionExamples class >> isAbstract [
	^ self name = #GtRemotePhlowWebBrowserStencilLocalInspectionExamples
]
